version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: course
    container_name: my-mysql-docker-compose
    volumes:
      - mysql-volume:/var/lib/mysql
  my-app:
    build: .
    image: my-app:v1.1
    ports:
      - 8888:8080
    container_name: my-app-docker-compose
    depends_on:
      - db
volumes:
  mysql-volume:


