INSERT INTO "user" (username, name, password, roles) VALUES ('nami', 'luis márquez', '$2a$10$9TU/nhqwqqNDfRx8Eg2Wvu9i/yd7UimLaLYigHaad8R/qLj7j4H72', 'ROLE_CUSTOMER');
INSERT INTO "user" (username, name, password, roles) VALUES ('robin', 'fulano pérez', '$2a$10$7Qsr4MRDTq4e.9ZjXgOvCu/0clEKlTGwtVlRMgi.wtB0AWiDISEx.', 'ROLE_ASSISTANT_ADMINISTRATOR');
INSERT INTO "user" (username, name, password, roles) VALUES ('zoro', 'zoro', '$2a$10$Eb11qu4GEU3dVJmUtnfaVOuK7f8aaOYWNdNlxWGSC2VCR87ckD8nC', 'ROLE_ADMINISTRATOR');

insert into category (name, status) values ('Alcentra Capital Corp.','ENABLED');
insert into category (name, status) values ('RiverNorth Opportunities Fund, Inc.','ENABLED');
insert into category (name, status) values ('Ligand Pharmaceuticals Incorporated','ENABLED');
insert into category (name, status) values ('Uranium Resources, Inc.','ENABLED');
insert into category (name, status) values ('SodaStream International Ltd.','ENABLED');


insert into product (name, price, status, category_id) values ('Pepperoni Slices', 435.8, 'ENABLED', 5);
insert into product (name, price, status, category_id) values ('Shallots', 451.93, 'ENABLED', 1);
insert into product (name, price, status, category_id) values ('Ice Cream - Super Sandwich', 235.34, 'ENABLED', 2);
insert into product (name, price, status, category_id) values ('Wine - Fume Blanc Fetzer', 240.63, 'ENABLED', 2);
insert into product (name, price, status, category_id) values ('Coffee Swiss Choc Almond', 204.0, 'ENABLED', 5);
insert into product (name, price, status, category_id) values ('Wine - Beaujolais Villages', 348.78, 'ENABLED', 4);
insert into product (name, price, status, category_id) values ('Milk - Skim', 289.95, 'ENABLED', 2);
insert into product (name, price, status, category_id) values ('Swordfish Loin Portions', 309.16, 'ENABLED', 3);
insert into product (name, price, status, category_id) values ('Beer - Mill St Organic', 245.41, 'ENABLED', 3);
insert into product (name, price, status, category_id) values ('Octopus - Baby, Cleaned', 462.55, 'ENABLED', 3);
insert into product (name, price, status, category_id) values ('Grenadine', 466.05, 'ENABLED', 1);
insert into product (name, price, status, category_id) values ('Eggplant - Baby', 140.74, 'ENABLED', 2);
insert into product (name, price, status, category_id) values ('Wine - Alsace Gewurztraminer', 158.07, 'ENABLED', 3);
insert into product (name, price, status, category_id) values ('Water - Spring 1.5lit', 100.29, 'ENABLED', 1);
insert into product (name, price, status, category_id) values ('Cherries - Fresh', 196.74, 'ENABLED', 4);
insert into product (name, price, status, category_id) values ('Soup - Campbells Asian Noodle', 258.09, 'ENABLED', 1);
insert into product (name, price, status, category_id) values ('Salt - Table', 231.86, 'ENABLED', 2);
insert into product (name, price, status, category_id) values ('Grapes - Black', 207.73, 'ENABLED', 4);
insert into product (name, price, status, category_id) values ('Goat - Whole Cut', 450.62, 'ENABLED', 5);
insert into product (name, price, status, category_id) values ('Venison - Liver', 352.68, 'ENABLED', 1);
insert into product (name, price, status, category_id) values ('Veal - Inside', 157.96, 'ENABLED', 2);
insert into product (name, price, status, category_id) values ('Wine - Placido Pinot Grigo', 420.56, 'ENABLED', 1);
insert into product (name, price, status, category_id) values ('Wine - Fume Blanc Fetzer', 370.72, 'ENABLED', 4);
insert into product (name, price, status, category_id) values ('Cafe Royale', 110.45, 'ENABLED', 4);
insert into product (name, price, status, category_id) values ('Lettuce - Lolla Rosa', 231.34, 'ENABLED', 5);
insert into product (name, price, status, category_id) values ('Wine - White, French Cross', 208.58, 'ENABLED', 1);
insert into product (name, price, status, category_id) values ('Foil Wrap', 477.38, 'ENABLED', 5);
insert into product (name, price, status, category_id) values ('Amarula Cream', 324.82, 'ENABLED', 3);
insert into product (name, price, status, category_id) values ('Juice - V8 Splash', 126.35, 'ENABLED', 2);
insert into product (name, price, status, category_id) values ('Scrubbie - Scotchbrite Hand Pad', 362.03, 'ENABLED', 2);
insert into product (name, price, status, category_id) values ('Trueblue - Blueberry', 342.95, 'ENABLED', 1);
insert into product (name, price, status, category_id) values ('Fork - Plastic', 117.8, 'ENABLED', 3);
insert into product (name, price, status, category_id) values ('Onion - Dried', 392.02, 'ENABLED', 5);
insert into product (name, price, status, category_id) values ('Beef - Bresaola', 117.49, 'ENABLED', 1);
insert into product (name, price, status, category_id) values ('Brandy - Bar', 416.86, 'ENABLED', 3);
insert into product (name, price, status, category_id) values ('Basil - Seedlings Cookstown', 384.61, 'ENABLED', 3);
insert into product (name, price, status, category_id) values ('Lettuce - Radicchio', 122.38, 'ENABLED', 2);
insert into product (name, price, status, category_id) values ('Tomato - Peeled Italian Canned', 394.04, 'ENABLED', 5);
insert into product (name, price, status, category_id) values ('Chicken - Whole Roasting', 366.51, 'ENABLED', 1);
insert into product (name, price, status, category_id) values ('Onions - Green', 343.27, 'ENABLED', 2);
insert into product (name, price, status, category_id) values ('Pork - Inside', 467.13, 'ENABLED', 4);
insert into product (name, price, status, category_id) values ('Ecolab Crystal Fusion', 136.57, 'ENABLED', 5);
insert into product (name, price, status, category_id) values ('Wine - Blue Nun Qualitatswein', 140.93, 'ENABLED', 5);
insert into product (name, price, status, category_id) values ('Soup - Campbells, Cream Of', 284.24, 'ENABLED', 5);
insert into product (name, price, status, category_id) values ('Dill Weed - Fresh', 321.67, 'ENABLED', 3);
insert into product (name, price, status, category_id) values ('Pears - Bartlett', 365.77, 'ENABLED', 5);
insert into product (name, price, status, category_id) values ('Bread - 10 Grain', 431.24, 'ENABLED', 2);
insert into product (name, price, status, category_id) values ('Table Cloth 120 Round White', 146.35, 'ENABLED', 4);
insert into product (name, price, status, category_id) values ('Pasta - Cheese / Spinach Bauletti', 189.38, 'ENABLED', 3);
insert into product (name, price, status, category_id) values ('Lettuce - Frisee', 227.64, 'ENABLED', 3);